arr = []
arr.extend(['E' for x in range(12)])
arr.extend(['A' for x in range(9)])
arr.extend(['I' for x in range(9)])
arr.extend(['O' for x in range(8)])
arr.extend(['N' for x in range(6)])
arr.extend(['R' for x in range(6)])
arr.extend(['T' for x in range(6)])
arr.extend(['L' for x in range(4)])
arr.extend(['S' for x in range(4)])
arr.extend(['U' for x in range(4)])
arr.extend(['D' for x in range(4)])
arr.extend(['G' for x in range(3)])
arr.extend(['B' for x in range(2)])
arr.extend(['C' for x in range(2)])
arr.extend(['M' for x in range(2)])
arr.extend(['P' for x in range(2)])
arr.extend(['F' for x in range(2)])
arr.extend(['H' for x in range(2)])
arr.extend(['V' for x in range(2)])
arr.extend(['W' for x in range(2)])
arr.extend(['Y' for x in range(2)])
arr.extend(['K' for x in range(1)])
arr.extend(['J' for x in range(1)])
arr.extend(['X' for x in range(1)])
arr.extend(['Q' for x in range(1)])
arr.extend(['Z' for x in range(1)])
arr.extend([' ' for x in range(2)])
import os, json
cwd = os.path.dirname(os.path.realpath(__file__)).replace('\\', '/')
json.dump(arr, open(f'{cwd}/word_distribution.json', 'w'), indent=4)
